on:
  push:
    branches: [ master ]

  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19
      - name: npm install and npm run CI commands
        run: |
          npm i -f
          npm run build:ci
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 88.99.65.110
          username: cicd@v1.zarei.xyz
          password: ${{ secrets.PASSWORD }}
          local-dir: ./dist/mahdi-zarei-portfolio/browser/
